### ISSUE TITLE
App with asynctask like Alamofire

### ISSUE THREAD

**Issue by massimilianochiodi** [KaneCheshire/Communicator#17]
Ciao, 
I'm designing an app that makes several asynchronous calls.

In practice, from wkApp I call iosApp with ImmediateMessage

In iosApp use Communicator.shared.immediateMessageReceivedObservers.add to listen to the receipt of the request from wkApp.

Once the request arrives, an 'alamofire' session starts which performs some work on its completion and should send the results to wkApp

Can I send the reply message to the first wkApp request later? or do I have to use a listener on wkApp that awaits the response from iosApp?

How can I do ?

Sorry for my English.. .

**Comment by KaneCheshire** [comment]
Hey! 

It depends how long you're expecting the async task to take, generally the reply handler should be used almost immediately if possible. Especially because if the screen turns off on the watch or the user lowers their wrist, the reply handler might not get called on the watch.

Probably I would suggest something like:

```swift
Communicator.shared.immediateMessageReceivedObservers.add { message in
  guard message.identifier == "my_id" else { return }
  Alamofire.perform {
    let reply = GuaranteedMessage(identifier: "", ...)
    try! Communicator.shared.send(reply)
  }
}
```

You could also check the current `reachability` to decide whether to use an `ImmediateMessage` or `GuaranteedMessage` as the reply.

Also note that I've been working on a big update to Communicator which changes the way you observe things, in Communicator 4 it will be something more like this:

```swift
ImmediateMessage.observe { message in
  guard message.identifier == "my_id" else { return }
  Alamofire.perform {
    let reply = GuaranteedMessage(identifier: "", ...)
    Communicator.shared.send(reply)
  }
}
```

Does this help?

**Comment by KaneCheshire** [comment]
Going to close this issue now :)
